### ISSUE TITLE
Opentrons Tip Rack doesnt import with protocol

### ISSUE THREAD

**Issue by ninjas28** [OndineBio/LaserProtocolDesigner#5]
When string in `enum LabwareType` is changed to `"Opentrons Tip Rack"` (with spaces), the tip rack no longer imports properly.

**Comment by ninjas28** [comment]
Will be fixed with next release.

**Comment by cadeo111** [comment]
fixed in 58e52ca2947ff3fd34affe583c6a3ffc7f82d1bf
